- name: Ensure custom CA folder exists
  ansible.builtin.file:
    path: "{{ custom_ca_path }}"
    state: directory

- name: Check if host private key already exists
  ansible.builtin.stat:
    path: "{{ private_key_path }}"
  register: private_key_stat

- name: Generate private key for host
  community.crypto.openssl_privatekey:
    path: "{{ private_key_path }}"
    mode: 0644
  when: not private_key_stat.stat.exists

- name: Check if host certificate already exists
  ansible.builtin.stat:
    path: "{{ cert_path }}"
  register: cert_path_stat

- name: Include local CA vars
  ansible.builtin.include_vars:
    file: ../../local-ca/vars/main.yml

- name: Generate host CSRs
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ private_key_path }}"
    subject_alt_name:
      - >
        {%- if host_names_are_public_dns -%}
          DNS:{{ inventory_hostname }}
        {%- else -%}
          IP:{{ ansible_default_ipv4.address }}
        {%- endif -%}
      # - "IP:{{ ansible_default_ipv4.address }}"
      # - "{% if ansible_default_ipv6.address is defined %}IP:{{ ansible_default_ipv6.address }}{% else %}omit{% endif %}" TODO This
  register: csr
  # when: not cert_path_stat.stat.exists

- name: Sign certificate with local CA
  community.crypto.x509_certificate_pipe:
    csr_content: "{{ csr.csr }}"
    provider: ownca
    ownca_path: "{{ ca_cert_path }}"
    ownca_privatekey_path: "{{ ca_key_path }}"
    ownca_privatekey_passphrase: "{{ ca_passphrase }}"
    ownca_not_after: "+3650d"
    ownca_not_before: "-1d"
  delegate_to: 127.0.0.1
  register: certificate
  # when: not cert_path_stat.stat.exists

- name: Save certificate to host
  ansible.builtin.copy:
    dest: "{{ cert_path }}"
    content: "{{ certificate.certificate }}"
  # when: not cert_path_stat.stat.exists

- name: Upload CA certificate to host
  ansible.builtin.copy:
    src: "{{ ca_cert_path }}"
    dest: "{{ custom_ca_path }}ca.pem"
    remote_src: false

- name: Merge certs to full chain
  ansible.builtin.shell:
    cmd: cat {{ cert_path }} {{ custom_ca_path }}ca.pem > {{ custom_ca_path }}fullchain.pem
